
name: Build and Release NBPxeServer

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0, v1.2.3, etc.
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    name: Build for ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - arch: x64
            python-arch: x64
            output-name: NBPxeServer-x64.exe
          - arch: x86
            python-arch: x86
            output-name: NBPxeServer-x86.exe

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.8 (${{ matrix.python-arch }})
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        architecture: ${{ matrix.python-arch }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka

    - name: Compile with Nuitka
      run: python -m nuitka --assume-yes-for-downloads --onefile --windows-console-mode=disable --enable-plugin=tk-inter --windows-uac-admin --output-dir=dist --output-filename=${{ matrix.output-name }} --windows-icon-from-ico=icon.ico NBPxeServer.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output-name }}
        path: dist/${{ matrix.output-name }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') # Only run for tags

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/**/*.exe
